//age class model
CREATE TABLE AGECLASS (
    ID NUMBERIC NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    TITLE TEXT,
    YEAR_FROM INTEGER,
    YEAR_TO INTEGER,
    BELONGS_TO_AGECLASSESDEFINITION INTEGER
);

